export const reportText = {
  subtitle: "مركز موحد لقراءة مؤشرات المبيعات والتشغيل من عقود الخادم.",
  refresh: "تحديث البيانات",
  filters: "فلاتر التقرير",
  filtersHint: "تطبق الفترة والفرع على جميع الجداول والرسوم في نفس التشغيل.",
  period: "الفترة",
  branch: "الفرع",
  allBranches: "كل الفروع المسموح بها",
  apply: "تطبيق",
  loading: "جارٍ تشغيل التقارير…",
  loadingCatalog: "جارٍ تحميل دليل التقارير والفروع…",
  loadError: "تعذر تحميل التقارير.",
  days7: "آخر 7 أيام",
  days30: "آخر 30 يومًا",
  days90: "آخر 90 يومًا",
  catalogTitle: "دليل التقارير المتاحة",
  catalogHint: "تعريفات ثابتة من الكود؛ لا SQL أو إعدادات تنفيذ حرة من الواجهة.",
  activeReports: "تقارير نشطة",
  operationalSummary: "ملخص التشغيل اليومي",
  salesTrend: "اتجاه المبيعات",
  salesTrendHint: "صافي المدفوعات المحصلة لكل يوم بعد أثر المرتجعات، وبدون unpaid.",
  salesBySource: "المبيعات حسب المصدر",
  noData: "لا توجد بيانات ضمن الفلاتر الحالية.",
  paymentMethod: "طريقة الدفع",
  product: "الصنف",
  grossItemSales: "إجمالي قيمة البنود",
  topProductsGrossHint: "قيمة Gross لبنود الطلبات غير الملغاة؛ لا تمثل صافي التحصيل بعد توزيع المرتجعات.",
  lastGenerated: "وقت إنشاء الاستجابة",
  timezone: "المنطقة الزمنية",
  timezonePolicy: "سياسة التوقيت",
  branchTimezone: "توقيت الفرع المحدد",
  accountDefaultTimezone: "توقيت الحساب الافتراضي لكل الفروع",
  requestId: "معرف الطلب",
  showChartData: "عرض جدول بيانات الرسم",
  item: "البند",
  value: "القيمة",
  categories: {
    salesOrders: "المبيعات والطلبات",
    productsMenu: "المنتجات والمنيو",
    shiftsCash: "الشيفتات والكاش",
    customers: "العملاء",
    inventory: "المخزون",
    kitchen: "المطبخ",
    finance: "المالية",
  },
} as const;
