/** نصوص الواجهة العربية — YKMS-01 (لا نصوص hardcoded داخل الصفحات) */
export const t = {
  appName: "YAKEBDA MS",
  appTagline: "نظام إدارة المطاعم",
  login: {
    title: "تسجيل الدخول",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    submit: "دخول",
    working: "جارٍ الدخول…",
  },
  nav: {
    dashboard: "لوحة التحكم",
    pos: "نقطة البيع",
    kitchen: "المطبخ",
    menu: "المنيو",
    orders: "الطلبات",
    tables: "الطاولات",
    customers: "العملاء",
    reports: "التقارير",
    settings: "الإعدادات",
    branches: "الفروع",
    users: "المستخدمون",
    devices: "الأجهزة",
    hardware: "الهاردوير",
    printJobs: "طابور الطباعة",
    apiClients: "عملاء API",
    audit: "سجل العمليات",
    logout: "خروج",
  },
  common: {
    add: "إضافة",
    edit: "تعديل",
    save: "حفظ",
    cancel: "إلغاء",
    name: "الاسم",
    empty: "لا توجد بيانات بعد — ابدأ بالإضافة.",
    createdAt: "تاريخ الإنشاء",
    active: "نشط",
    inactive: "متوقف",
  },
  branches: {
    title: "الفروع",
    add: "إضافة فرع",
    address: "العنوان",
    timezone: "المنطقة الزمنية",
  },
  users: {
    title: "المستخدمون",
    add: "إضافة مستخدم",
    email: "البريد الإلكتروني",
    password: "كلمة المرور (للإدارة)",
    pin: "رمز PIN (للكاشير/الويتر)",
    role: "الدور",
    roles: "الأدوار",
  },
  devices: {
    title: "الأجهزة",
    add: "تسجيل جهاز",
    branch: "الفرع",
    type: "نوع الجهاز",
    lastSeen: "آخر ظهور",
    types: {
      pos: "كاشير POS",
      kds: "شاشة مطبخ KDS",
      waiter: "جهاز ويتر",
      customer_display: "شاشة عميل",
      kitchen_printer: "طابعة مطبخ",
      receipt_printer: "طابعة إيصالات",
    } as Record<string, string>,
  },
  hardware: {
    title: "نقاط الهاردوير",
    add: "إضافة نقطة هاردوير",
    kind: "النوع",
    connection: "الاتصال",
    device: "جهاز الجسر",
    kinds: {
      receipt_printer: "طابعة إيصالات",
      kitchen_printer: "طابعة مطبخ",
      cash_drawer: "درج كاش",
      customer_display: "شاشة عميل",
      barcode_scanner: "قارئ باركود",
    } as Record<string, string>,
  },
  printJobs: {
    title: "طابور الطباعة",
    test: "طباعة تجريبية",
    endpoint: "نقطة الهاردوير",
    type: "النوع",
    status: "الحالة",
    statuses: {
      pending: "بالانتظار",
      printing: "قيد الطباعة",
      printed: "تمت الطباعة",
      failed: "فشلت",
    } as Record<string, string>,
  },
  apiClients: {
    title: "عملاء API والرموز",
    add: "إضافة عميل API",
    kind: "النوع",
    newToken: "إنشاء رمز",
    tokenOnce: "انسخ الرمز الآن — لن يظهر مرة أخرى:",
    kinds: {
      website: "الموقع",
      qr: "QR",
      mobile: "تطبيق موبايل",
      bridge: "جسر الأجهزة Bridge",
      other: "أخرى",
    } as Record<string, string>,
  },
  audit: {
    title: "سجل العمليات",
    user: "المستخدم",
    action: "الإجراء",
    branch: "الفرع",
    device: "الجهاز",
    time: "الوقت",
  },
  menu: {
    title: "المنيو",
    categories: "الفئات",
    products: "الأصناف",
    groups: "مجموعات الإضافات",
    branch: "أسعار وإتاحة الفروع",
    preview: "معاينة المنيو",
    addCategory: "إضافة فئة",
    addProduct: "إضافة صنف",
    addGroup: "إضافة مجموعة",
    addModifier: "إضافة إضافة",
    addVariant: "إضافة حجم/نوع",
    nameAr: "الاسم بالعربية",
    price: "السعر",
    priceDelta: "فرق السعر",
    basePrice: "السعر الأساسي",
    priceOverride: "سعر الفرع (اتركه فارغًا للأساسي)",
    category: "الفئة",
    sortOrder: "الترتيب",
    variants: "الأحجام/الأنواع",
    linkedGroups: "مجموعات الإضافات المرتبطة",
    available: "متاح",
    unavailable: "غير متاح",
    availabilityNote: "ملاحظة الإتاحة",
    chooseBranch: "اختر الفرع",
    minSelect: "أقل اختيار",
    maxSelect: "أقصى اختيار",
    required: "إلزامي",
  },
  pos: {
    title: "نقطة البيع",
    search: "ابحث عن صنف…",
    cart: "الطلب الحالي",
    emptyCart: "لم تتم إضافة أصناف بعد.",
    qty: "الكمية",
    itemNotes: "ملاحظات الصنف",
    orderNotes: "ملاحظات الطلب",
    discount: "الخصم",
    deliveryFee: "رسوم التوصيل",
    deliveryAddress: "عنوان التوصيل",
    orderType: "نوع الطلب",
    dineIn: "صالة",
    takeaway: "تيك أواي",
    delivery: "دليفري",
    table: "الطاولة",
    customer: "العميل",
    payment: "طريقة الدفع",
    shift: "الشيفت",
    openShift: "فتح شيفت",
    closeShift: "إغلاق الشيفت",
    cashIn: "إضافة نقدية",
    cashOut: "سحب نقدية",
    openingCash: "رصيد بداية الشيفت",
    actualCash: "النقدية الفعلية",
    expectedCash: "النقدية المتوقعة",
    currentShift: "الشيفت الحالي",
    noShift: "لا يوجد شيفت مفتوح. افتح شيفت قبل تسجيل دفع نقدي.",
    shiftOpened: "الشيفت مفتوح",
    cashReason: "سبب الحركة",
    cash: "نقدي",
    card: "بطاقة",
    wallet: "محفظة",
    unpaid: "غير مدفوع",
    subtotal: "الإجمالي الفرعي",
    total: "الإجمالي",
    submit: "إرسال الطلب",
    clear: "تفريغ السلة",
    chooseOptions: "اختر التفاصيل",
    addToCart: "إضافة للطلب",
    orderCreated: "تم إنشاء الطلب رقم",
    printReceipt: "طباعة الإيصال",
    previewReceipt: "معاينة الإيصال",
    close: "إغلاق",
  },
  kitchen: {
    title: "شاشة المطبخ",
    startPrep: "بدء التحضير",
    ready: "جاهز",
    complete: "مكتمل",
    empty: "لا توجد طلبات في المطبخ حاليًا.",
    orderNo: "طلب",
    notes: "ملاحظات",
  },
  orders: {
    title: "الطلبات",
    orderNo: "رقم الطلب",
    type: "النوع",
    status: "الحالة",
    total: "الإجمالي",
    branch: "الفرع",
    cancel: "إلغاء الطلب",
    cancelReason: "سبب الإلغاء",
    payments: "المدفوعات",
    addPayment: "تسجيل دفعة",
    details: "تفاصيل الطلب",
    statuses: {
      draft: "مسودة",
      submitted: "تم الإرسال",
      in_kitchen: "في المطبخ",
      ready: "جاهز",
      completed: "مكتمل",
      cancelled: "ملغي",
    } as Record<string, string>,
    types: {
      dine_in: "صالة",
      takeaway: "تيك أواي",
      delivery: "دليفري",
    } as Record<string, string>,
  },
  tables: {
    title: "الطاولات",
    add: "إضافة طاولة",
    seats: "المقاعد",
    startOrder: "فتح طلب",
    statuses: {
      available: "متاحة",
      occupied: "مشغولة",
      reserved: "محجوزة",
      cleaning: "تنظيف",
    } as Record<string, string>,
  },
  customers: {
    title: "العملاء",
    add: "إضافة عميل",
    phone: "رقم الهاتف",
    address: "العنوان",
    notes: "ملاحظات",
    search: "بحث بالاسم أو الهاتف…",
  },
  reports: {
    title: "التقارير",
    salesToday: "مبيعات اليوم",
    ordersToday: "طلبات اليوم",
    openOrders: "طلبات مفتوحة",
    kitchenPending: "قيد التحضير",
    cancelledToday: "ملغاة اليوم",
    openShifts: "شيفتات مفتوحة",
    openShiftCashSales: "نقدية الشيفت المفتوح",
    topProducts: "أفضل الأصناف",
    paymentMethods: "طرق الدفع",
    salesByBranch: "المبيعات حسب الفرع",
    qty: "الكمية",
    totalSales: "إجمالي المبيعات",
    count: "عدد العمليات",
    egp: "ج.م",
  },
  receipt: {
    branch: "الفرع",
    orderNo: "طلب رقم",
    date: "التاريخ",
    subtotal: "الإجمالي الفرعي",
    discount: "الخصم",
    deliveryFee: "رسوم التوصيل",
    total: "الإجمالي",
    payment: "طريقة الدفع",
    notes: "ملاحظات",
  },
} as const;

export const fmtTime = (v?: string | null) =>
  v ? new Date(v).toLocaleString("ar-EG", { dateStyle: "short", timeStyle: "short" }) : "—";
