import { Knex } from "knex";

/**
 * YKMS-01 + YKMS-01H foundation schema.
 * IDs are UUIDs generated by the application (crypto.randomUUID).
 */
export async function up(db: Knex): Promise<void> {
  await db.schema.createTable("accounts", (t) => {
    t.uuid("id").primary();
    t.string("name").notNullable(); // اسم المطعم
    t.string("default_locale").notNullable().defaultTo("ar");
    t.string("default_dir").notNullable().defaultTo("rtl");
    t.string("numerals").notNullable().defaultTo("arabic"); // arabic | latin
    t.timestamps(true, true);
  });

  await db.schema.createTable("branches", (t) => {
    t.uuid("id").primary();
    t.uuid("account_id").notNullable().references("accounts.id");
    t.string("name").notNullable();
    t.string("address").nullable();
    t.string("timezone").notNullable().defaultTo("Africa/Cairo");
    t.boolean("is_active").notNullable().defaultTo(true);
    t.timestamps(true, true);
  });

  await db.schema.createTable("users", (t) => {
    t.uuid("id").primary();
    t.uuid("account_id").notNullable().references("accounts.id");
    t.uuid("branch_id").nullable().references("branches.id");
    t.string("name").notNullable();
    t.string("email").nullable().unique();
    t.string("password_hash").nullable(); // دخول الإدارة — FR-011
    t.string("pin_hash").nullable(); // دخول الكاشير/الويتر — FR-012
    t.boolean("is_active").notNullable().defaultTo(true);
    t.timestamps(true, true);
  });

  await db.schema.createTable("roles", (t) => {
    t.uuid("id").primary();
    t.uuid("account_id").notNullable().references("accounts.id");
    t.string("key").notNullable(); // owner, manager, cashier...
    t.string("name_ar").notNullable();
    t.boolean("is_system").notNullable().defaultTo(false);
    t.timestamps(true, true);
    t.unique(["account_id", "key"]);
  });

  await db.schema.createTable("permissions", (t) => {
    t.string("key").primary(); // e.g. branches.manage
    t.string("name_ar").notNullable();
    t.string("group").notNullable();
  });

  await db.schema.createTable("role_permissions", (t) => {
    t.uuid("role_id").notNullable().references("roles.id").onDelete("CASCADE");
    t.string("permission_key").notNullable().references("permissions.key");
    t.primary(["role_id", "permission_key"]);
  });

  await db.schema.createTable("user_roles", (t) => {
    t.uuid("user_id").notNullable().references("users.id").onDelete("CASCADE");
    t.uuid("role_id").notNullable().references("roles.id").onDelete("CASCADE");
    t.primary(["user_id", "role_id"]);
  });

  // ---- devices (FR-002 / FR-004) ----
  await db.schema.createTable("devices", (t) => {
    t.uuid("id").primary();
    t.uuid("account_id").notNullable().references("accounts.id");
    t.uuid("branch_id").notNullable().references("branches.id");
    t.string("name").notNullable();
    t.string("type").notNullable(); // pos | kds | waiter | customer_display | kitchen_printer | receipt_printer
    t.string("platform").notNullable().defaultTo("windows");
    t.string("status").notNullable().defaultTo("registered"); // registered | online | offline
    t.timestamp("last_seen_at").nullable();
    t.timestamps(true, true);
  });

  // ---- YKMS-01H ----
  await db.schema.createTable("device_profiles", (t) => {
    t.uuid("id").primary();
    t.uuid("device_id").notNullable().references("devices.id").onDelete("CASCADE");
    t.string("name").notNullable();
    t.jsonb("settings").notNullable().defaultTo("{}"); // locale, numerals, default printer, kiosk...
    t.boolean("is_active").notNullable().defaultTo(true);
    t.timestamps(true, true);
  });

  await db.schema.createTable("hardware_endpoints", (t) => {
    t.uuid("id").primary();
    t.uuid("branch_id").notNullable().references("branches.id");
    t.uuid("device_id").nullable().references("devices.id"); // the Windows machine hosting the bridge
    t.string("name").notNullable();
    t.string("kind").notNullable(); // receipt_printer | kitchen_printer | cash_drawer | customer_display | barcode_scanner
    t.string("connection").notNullable(); // usb | lan | bluetooth | windows_driver
    t.string("protocol").notNullable().defaultTo("escpos"); // escpos | windows_driver
    t.string("address").nullable(); // IP, share name, COM port...
    t.string("station").nullable(); // kitchen station key (later YKMS-04)
    t.boolean("is_active").notNullable().defaultTo(true);
    t.timestamp("last_seen_at").nullable();
    t.timestamps(true, true);
  });

  await db.schema.createTable("print_jobs", (t) => {
    t.uuid("id").primary();
    t.uuid("branch_id").notNullable().references("branches.id");
    t.uuid("endpoint_id").notNullable().references("hardware_endpoints.id");
    t.uuid("device_id").nullable().references("devices.id");
    t.string("type").notNullable(); // receipt | kitchen_ticket | test
    t.jsonb("payload").notNullable().defaultTo("{}"); // rendered lines / template data (Arabic)
    t.string("status").notNullable().defaultTo("pending"); // pending | printing | printed | failed  (FR-071)
    t.string("error").nullable();
    t.integer("attempts").notNullable().defaultTo(0);
    t.uuid("created_by").nullable().references("users.id");
    t.timestamp("printed_at").nullable();
    t.timestamps(true, true);
    t.index(["status", "endpoint_id"]);
  });

  await db.schema.createTable("audit_logs", (t) => {
    t.uuid("id").primary();
    t.uuid("account_id").nullable();
    t.uuid("branch_id").nullable();
    t.uuid("device_id").nullable();
    t.uuid("user_id").nullable();
    t.uuid("api_client_id").nullable();
    t.string("action").notNullable(); // auth.login, branch.create, print_job.create...
    t.string("entity_type").nullable();
    t.uuid("entity_id").nullable();
    t.jsonb("meta").notNullable().defaultTo("{}");
    t.string("ip").nullable();
    t.timestamp("created_at").notNullable().defaultTo(db.fn.now());
    t.index(["account_id", "created_at"]);
  });

  // ---- API v1 foundation (FR-160..164) ----
  await db.schema.createTable("api_clients", (t) => {
    t.uuid("id").primary();
    t.uuid("account_id").notNullable().references("accounts.id");
    t.string("name").notNullable();
    t.string("kind").notNullable(); // website | qr | mobile | bridge | other
    t.boolean("is_active").notNullable().defaultTo(true);
    t.timestamps(true, true);
  });

  await db.schema.createTable("api_tokens", (t) => {
    t.uuid("id").primary();
    t.uuid("client_id").notNullable().references("api_clients.id").onDelete("CASCADE");
    t.string("name").notNullable();
    t.string("token_hash").notNullable().unique(); // NFR-003: never stored in plain text
    t.string("prefix").notNullable();
    t.jsonb("scopes").notNullable().defaultTo("[]"); // e.g. ["bridge"], ["orders.read"]
    t.timestamp("last_used_at").nullable();
    t.timestamp("revoked_at").nullable();
    t.timestamp("created_at").notNullable().defaultTo(db.fn.now());
  });

  await db.schema.createTable("integration_logs", (t) => {
    t.uuid("id").primary();
    t.uuid("api_client_id").nullable().references("api_clients.id");
    t.string("method").notNullable();
    t.string("path").notNullable();
    t.integer("status_code").notNullable();
    t.jsonb("meta").notNullable().defaultTo("{}");
    t.timestamp("created_at").notNullable().defaultTo(db.fn.now());
  });
}

export async function down(db: Knex): Promise<void> {
  const tables = [
    "integration_logs",
    "api_tokens",
    "api_clients",
    "audit_logs",
    "print_jobs",
    "hardware_endpoints",
    "device_profiles",
    "devices",
    "user_roles",
    "role_permissions",
    "permissions",
    "roles",
    "users",
    "branches",
    "accounts",
  ];
  for (const t of tables) await db.schema.dropTableIfExists(t);
}
